# 公共配置

server:
  address: 0.0.0.0
  port: ${port:8070}

spring:

  redis:
      # Redis服务器地址
      host: 120.132.29.90
      # Redis服务器连接端口
      port: 7389
      # Redis服务器连接密码（默认为空）
      password: 4cj34t4j9
      # 连接池最大连接数（使用负值表示没有限制）

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-init-sql: select count(1) from t_item
      idle-timeout: 10000
      max-lifetime: 180000
      validation-timeout: 5000
      minimum-idle: 20
      connection-timeout: 6000

ronglian:
  app-id: 8a216da86077dcd00160788b18b70112
  account-sid: 8a216da857511049015774861894153f
  auth-token: 396ac293985c7ad33359d276c6a3b4eb
  sms-tpls:
    captcha-id: 225789          # 登录短信
    consume-success-id: 225523  # 抢购成功通知
    delivery-success-id: 225525  # 配送通知

qiniu:
  bucket: menuxx
  access-key: sr4H3rnxg3fkN9bf5NBTj9V9ptPFMnW5Ryxbg_o6
  secret-key: 9Gtvk0QbjvLDKWXwAi_WCYQkLq5Biu-X9wjHjXS5

aliyun:
  ons:
    # 队列基础配置
    access-key-id: LTAIJ3GVZZrQhLcZ
    access-key-secret: FBS4lFAG7mq0h4cLikCCmAAoIeaBMF

    # 支付队列
    pay-topic-name: Topic_pay_yth
    pay-producer-id: PID_pay_yth
    pay-consumer-id: CID_pay_yth

    # 抢书渠道状态实时监控队列
    consume-obtain-topic-name: Topic_consume_obtain_yth
    consume-obtain-producer-id: PID_consume_obtain_yth
    consume-obtain-consumer-id: CID_consume_obtain_yth

    # 抢书削峰队列
    obtain-item-topic-name: Topic_obtain_item_yth
    obtain-item-producer-id: PID_obtain_item_yth
    obtain-item-consumer-id: CID_obtain_item_yth

    # 发送短信或者邮箱或者的队列
    # tag : sms 短信, mail 邮件消息
    sender-topic-name: Sender_topic_yth
    sender-producer-id: PID_sender_yth
    sender-consumer-id: CID_sender_yth

weixin:
  mp:
    app-id: wx931d9dfbd5275c6e
    app-secret: 5882869733213d929bee994933dae42b
    token: cf24c5cb8696f0e6566d2d504be9dd70
    aes-key: cf24c5cb8696f0e6566d2d504be9dd70
  pay:
    notify-url: http://wxtest.qurenjia.com/api/weixin_event_handler/pay_notify
    mch-id: 1487141332
    pay-secret: C63230BFEAAF1915494D2AA123832B34

auth-token:
  secret: ewydjwiefj23fg2y12g7e
  header: X-Authorization
  expiration: 7200