
auth-token:
  secret: qidj983f8u2dh2

spring:

  datasource:
    url: jdbc:mysql://rm-uf68lsw07o293t779o.mysql.rds.aliyuncs.com/onecode?characterEncoding=UTF-8
    password: B5q0n6NfDdvYWXD
    username: oc

  data:
    mongodb:
      host: 116.62.57.229
      port: 27017
      database: sx_test
      username: sx_u_test
      password: sx_p_test

  rabbitmq:
    host: msg.qurenjia.com
    port: 5672
    virtual-host: test1
    username: yth_test
    password: yth_test
    listener:
      simple:
        transaction-size: 10
        acknowledge-mode: auto
        prefetch: 10
        concurrency: 2
        max-concurrency: 5

logging:
  level:
    com.menuxx: DEBUG
    com.aliyun: DEBUG
    org.springframework: DEBUG
    org.springframework.amqp: ERROR
    org.jooq: DEBUG