
spring:

  freemarker:
    template-loader-path: classpath:/views/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

  # REDIS (RedisProperties)
  # Redis数据库索引（默认为0）
  redis:
    database: 10
    # Redis服务器地址
    host: 120.132.29.90
    # Redis服务器连接端口
    port: 7389
    # Redis服务器连接密码（默认为空）
    password: 4cj34t4j9
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 2
    url: redis://:4cj34t4j9@120.132.29.90:7389/10

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: B5q0n6NfDdvYWXD
    username: oc
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://rm-uf68lsw07o293t779o.mysql.rds.aliyuncs.com/onecode?characterEncoding=UTF-8
    hikari:
      maximum-pool-size: 10
      connection-init-sql: select count(1) from t_item
      idle-timeout: 10000
      max-lifetime: 180000
      validation-timeout: 5000
      minimum-idle: 20
      connection-timeout: 6000

ronglian:
  app-id: 8a216da85da6adf7015de9addca8199f
  account-sid: 8a216da857511049015774861894153f
  auth-token: e1de26cde6e24dd28dfedcd81467d1f0
  sms-tpls:
    captcha-id: 198719
    consume-success-id: 221811  # 抢购成功通知
    delivery-success-id: 225360  # 配送通知

qiniu:
  bucket: menuxx
  access-key: sr4H3rnxg3fkN9bf5NBTj9V9ptPFMnW5Ryxbg_o6
  secret-key: 9Gtvk0QbjvLDKWXwAi_WCYQkLq5Biu-X9wjHjXS5

aliyun:
  ons:
    # 队列基础配置
    access-key-id: LTAIJ3GVZZrQhLcZ
    access-key-secret: FBS4lFAG7mq0h4cLikCCmAAoIeaBMF

    # 全局无序 topic
    public-topic: PublicTopic
    # 全局无序生产者
    public-producer-id: PID_public_yth
    public-consumer-id: CID_public_yth

    # 分区有序 topic
    sharding-order-topic: ShardingOrderTopic
    sharding-order-producer-id: PID_sharding_order
    sharding-order-consumer-id: CID_sharding_order

weixin:
  mp:
    app-id: wx931d9dfbd5275c6e
    app-secret: 5882869733213d929bee994933dae42b
    token: cf24c5cb8696f0e6566d2d504be9dd70
    aes-key: cf24c5cb8696f0e6566d2d504be9dd70
  pay:
    notify-url: http://wxtest.qurenjia.com/weixin_event_handler/pay_notify
    mch-id: 1486563372
    pay-secret: 3444F98CD4AB436BBC180085EF4C9S9A

auth-token:
  secret: ewydjwiefj23fg2y12g7e
  header: X-Authorization
  expiration: 7200

server:
  address: 0.0.0.0
  port: ${port:8070}