
server:
  address: 0.0.0.0
  port: ${port:8071}

app:
  code-base-url: http://c.nizhuantech.com/c/

auth-token:
  secret: 8dyh1o1fh923dh2dui112dhid823di23ihi21ksqad

spring:

  session:
    store-type: redis

  # REDIS (RedisProperties)
  # Redis数据库索引（默认为0）
  redis:
    database: 11
    pool:
      max-active: 10
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 10
      # 连接池中的最大空闲连接
      max-idle: 20
      # 连接池中的最小空闲连接
      min-idle: 10
    url: redis://:4cj34t4j9@116.62.57.229:7389/11

  datasource:
    url: jdbc:mysql://10.23.84.153/xueren?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: xueren_prod
    password: 'pBZNEfwddnxzGXkc'
    hikari:
      maximum-pool-size: 50

  rabbitmq:
    host: msg.qurenjia.com
    port: 5672
    virtual-host: xueren
    username: xueren
    password: xueren001
    listener:
      simple:
        transaction-size: 20
        acknowledge-mode: auto
        prefetch: 20
        concurrency: 2
        max-concurrency: 5
        default-requeue-rejected: false

  data:
    mongodb:
      host: 116.62.57.229
      port: 27017
      database: xueren_read
      username: api-server
      password: '&asNh$80d!asd'

weixin:
  pay:
    notify-url: http://wx.nizhuantech.com/api/weixin_event_handler/pay_notify

logging:
  level:
    com.menuxx: INFO