
app:
  code-base-url: http://c.nizhuantech.com/tc/

auth-token:
  secret: qidj983f8u2dh2

spring:

  session:
    store-type: redis

  redis:
    database: 10
    pool:
      max-active: 10
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 1
      # 连接池中的最大空闲连接
      max-idle: 5
      # 连接池中的最小空闲连接
      min-idle: 2
    url: redis://:4cj34t4j9@120.132.29.90:7389/10

  datasource:
    url: jdbc:mysql://rm-uf68lsw07o293t779o.mysql.rds.aliyuncs.com/onecode?characterEncoding=UTF-8
    username: oc
    password: B5q0n6NfDdvYWXD
    hikari:
      maximum-pool-size: 10

  data:
    mongodb:
      host: 116.62.57.229
      port: 27017
      database: sx_test
      username: sx_u_test
      password: sx_p_test

  rabbitmq:
    host: msg.qurenjia.com
    port: 5672
    virtual-host: test1
    username: yth_test
    password: yth_test
    listener:
      simple:
        transaction-size: 10
        acknowledge-mode: auto
        prefetch: 10
        concurrency: 2
        max-concurrency: 5

logging:
  level:
    com.menuxx: DEBUG
    com.aliyun: DEBUG
    org.springframework: DEBUG
    org.springframework.amqp: ERROR
    org.jooq: DEBUG