# 公共配置

server:
  address: 0.0.0.0
  port: ${port:8070}

spring:

  session:
    store-type: redis

  redis:
      # Redis服务器地址
      host: 116.62.57.229
      # Redis服务器连接端口
      port: 7389
      # Redis服务器连接密码（默认为空
      password: 4cj34t4j9
      # 连接池最大连接数（使用负值表示没有限制）

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-init-sql: select count(1) from t_item
      idle-timeout: 10000
      max-lifetime: 180000
      validation-timeout: 5000
      minimum-idle: 20
      connection-timeout: 6000
  jackson:
    time-zone: GMT+8


ronglian:
  app-id: 8a216da86077dcd00160788b18b70112
  account-sid: 8a216da857511049015774861894153f
  auth-token: e1de26cde6e24dd28dfedcd81467d1f0
  sms-tpls:
    captcha-id: 228587          # 登录短信
    consume-success-id: 228580  # 抢购成功通知
    delivery-success-id: 228581  # 配送通知

qiniu:
  bucket: menuxx
  access-key: sr4H3rnxg3fkN9bf5NBTj9V9ptPFMnW5Ryxbg_o6
  secret-key: 9Gtvk0QbjvLDKWXwAi_WCYQkLq5Biu-X9wjHjXS5

weixin:

  mini-app:
    app-id: wx931d9dfbd5275c6e
    app-secret: b30904dde6054224d33571bde3084b9c
    token: cf24c5cb8696f0e6566d2d504be9dd70
    aes-key: 656c9fcf24c5cb8696f0e72881306fc9af
    msg-data-format: JSON

  mini-app-pay:
    notify-url: http://wxtest.qurenjia.com/api/weixin_event_handler/pay_notify
    mch-id: 1486563372
    pay-secret: 3444F98CD4AB436BBC180085EF4C9S9A

  mp:
    app-id: wx3d87bb42c08a2c4b
    app-secret: 80160c2f8e9b3cb74c505f597c274130
    token: cf24c5cb8696f0e6566d2d504be9dd70
    aes-key: cf24c5cb8696f0e6566d2d504be9dd70

  mp-pay:
    notify-url: http://wxtest.qurenjia.com/api/weixin_event_handler/pay_notify
    mch-id: 1496051492
    pay-secret: 54F9AA22DACB17FE29EA5869CDF13221

auth-token:
  secret: ewydjwiefj23fg2y12g7e
  header: X-Authorization
  expiration: 7200